/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWeeklyPlannerRouteImport } from './routes/_authenticated.weekly-planner'
import { Route as AuthenticatedScheduleHealthRouteImport } from './routes/_authenticated.schedule-health'
import { Route as AuthenticatedDrawingsRouteImport } from './routes/_authenticated.drawings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedStationsStationIdRouteImport } from './routes/_authenticated.stations.$stationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeeklyPlannerRoute =
  AuthenticatedWeeklyPlannerRouteImport.update({
    id: '/weekly-planner',
    path: '/weekly-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleHealthRoute =
  AuthenticatedScheduleHealthRouteImport.update({
    id: '/schedule-health',
    path: '/schedule-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDrawingsRoute = AuthenticatedDrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStationsStationIdRoute =
  AuthenticatedStationsStationIdRouteImport.update({
    id: '/stations/$stationId',
    path: '/stations/$stationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/drawings': typeof AuthenticatedDrawingsRoute
  '/schedule-health': typeof AuthenticatedScheduleHealthRoute
  '/weekly-planner': typeof AuthenticatedWeeklyPlannerRoute
  '/stations/$stationId': typeof AuthenticatedStationsStationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/drawings': typeof AuthenticatedDrawingsRoute
  '/schedule-health': typeof AuthenticatedScheduleHealthRoute
  '/weekly-planner': typeof AuthenticatedWeeklyPlannerRoute
  '/': typeof AuthenticatedIndexRoute
  '/stations/$stationId': typeof AuthenticatedStationsStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/drawings': typeof AuthenticatedDrawingsRoute
  '/_authenticated/schedule-health': typeof AuthenticatedScheduleHealthRoute
  '/_authenticated/weekly-planner': typeof AuthenticatedWeeklyPlannerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/stations/$stationId': typeof AuthenticatedStationsStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/drawings'
    | '/schedule-health'
    | '/weekly-planner'
    | '/stations/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/drawings'
    | '/schedule-health'
    | '/weekly-planner'
    | '/'
    | '/stations/$stationId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/drawings'
    | '/_authenticated/schedule-health'
    | '/_authenticated/weekly-planner'
    | '/_authenticated/'
    | '/_authenticated/stations/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weekly-planner': {
      id: '/_authenticated/weekly-planner'
      path: '/weekly-planner'
      fullPath: '/weekly-planner'
      preLoaderRoute: typeof AuthenticatedWeeklyPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule-health': {
      id: '/_authenticated/schedule-health'
      path: '/schedule-health'
      fullPath: '/schedule-health'
      preLoaderRoute: typeof AuthenticatedScheduleHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drawings': {
      id: '/_authenticated/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof AuthenticatedDrawingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stations/$stationId': {
      id: '/_authenticated/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof AuthenticatedStationsStationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDrawingsRoute: typeof AuthenticatedDrawingsRoute
  AuthenticatedScheduleHealthRoute: typeof AuthenticatedScheduleHealthRoute
  AuthenticatedWeeklyPlannerRoute: typeof AuthenticatedWeeklyPlannerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStationsStationIdRoute: typeof AuthenticatedStationsStationIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDrawingsRoute: AuthenticatedDrawingsRoute,
  AuthenticatedScheduleHealthRoute: AuthenticatedScheduleHealthRoute,
  AuthenticatedWeeklyPlannerRoute: AuthenticatedWeeklyPlannerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStationsStationIdRoute: AuthenticatedStationsStationIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
